#
# Count of nodes assigned to task.
nodes: 1
#
# Count of CPU cores per node.
cpus_per_node: 4
#
# Count of GPU units per node.
gpus_per_node: 1
#
# Memory per node [GB].
mem_per_node: 16
#
# Walltime of slurm job.
time: 00-08:00:00

cluster_specific:
  # Slurm partition.
  # plgrid-gpu | plgrid-gpu-v100
  partition: plgrid-gpu-v100
  #
  # Enable local filesystem.
  constraint: localfs